site_name: Traffic Operations Infrastructure
theme:
  name: material
  logo: images/odi-square_logomark-blue.svg
  favicon: images/odi-circle_logomark-blue.png
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - footnotes
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      auto_title: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Introduction: index.md
  - Setup: setup.md
  - Writing Documentation: writing-documentation.md
  - Data Loading: data-loading.md
  - Incremental Models: incremental-models.md
  - Data Relay: data/data-relay.md
  - Data Warehouse Performance: data-warehouse-performance.md
  - dbt Project: dbt_docs/index.html
  - Data Analysis:
      - Exploratory Data Analysis: data/exploratory-data-analysis.md
      - Imputation: data/imputation.md
